services:
  - type: web
    name: inventory-management-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    
  - type: web
    name: inventory-management-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
